### ISSUE TITLE
problem with the starting

### ISSUE THREAD

**Issue by MoonieC** [arhik/DDPG_HFO#2]
Hi @arhik , I am faced with the following scene and I'd like to ask you how to solve this problem.

![image](https://user-images.githubusercontent.com/59831989/85570532-ff560100-b665-11ea-951f-91efba1162f5.png)

**Comment by arhik** [comment]
@MoonieC  https://github.com/LARG/HFO/tree/master/bin/teams/base/config/formations-dt

The configs are same as in Original HFO repo. Sorry for late reply.
